const cars: any[] = [
  {
    name: "Vauxhall Astra",
    make: "VAUXHALL",
    model: "ASTRA EXCITE",
    price: "£3,695",
    year: "2015",
    miles: "94,662",
    isMotd: true,
    motExpiryDate: "1 May 2026",
    isTaxed: false,
    taxExpiryDate: "19 April 2025",
    fuelType: "Petrol",
    engineSize: "1.6L",
    noOfOwners: 1,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "1 OWNER-FSH-JUST SVC'D-NEW MOT. **DUE TO BUILDING WORK WE ARE CLOSED UNTIL 1st JULY** 1 OWNER - FULL SERVICE HISTORY INCLUDING CAMBELT - JUST SERVICED WITH A NEW MOT - DRIVE AWAY TODAY! If you are looking for a well looked after Astra then look no further than this! It is in lovely condition inside and out, is in the sought after black with the tinted windows and alloys wheels and has full, comprehensive service history including all the invoices! It also had the cambelt changed in August 2021 and has just been serviced with a new MOT. The tyres are all good (OSF tyre replaced as per the MOT) and the body work is in great condition as is the interior and it has bluetooth, cruise control, speed limiter, ice cold air-conditioning and so much more! The car is ready now so why not book a viewing and test drive! At Hill View Cars we like to think we have a slightly different approach to selling cars. All our cars are valeted, serviced (if due), have a long or new MOT and are Experian checked to ensure they are HPI clear prior to you viewing them. This means that in most cases the cars are ready for you to drive away on the day. We also provide warranties through Warranty Solutions Group, one of the leading providers in the motor industry, and in many cases these warranties are extendable for a small additional premium. We are open 6 days a week (closed Sundays) however, as we are a small business and can’t always be on site we are APPOINTMENT ONLY to save disappointment. Please call us on 07412 693302 (preferred) or 01604 781708 to arrange a test drive and to ensure the car you are interested in is still available. We accept all major credit and debit cards and Part Exchange is welcome. We also now offer a delivery service countrywide, just ask us for a quote! Visit our Facebook page to see what our customers say about us: www.facebook.com/HillViewCarsNorthamtonshire/. If you can't see the car you want why not give us a call to discuss your requirements and be at the head of the queue as new stock arrives! Hill View Cars, car sales with a conscience. Vehicle registered: 30/06/2015. Buying with Hill View Cars. Hill View Cars is a family run business in a village location. We were established in 2015 and supply above average cars at affordable prices with most being ready to drive away. We pride ourselves on quality and service and would be happy to discuss your vehicle requirements with you as we know buying a car can be a personal and emotional experience.",
    colour: "Black",
    location: "(Hill View Cars) 57 mins away from PE2 8WS. NN6 9QW",
  },
  {
    name: "Vauxhall Corsa",
    make: "VAUXHALL",
    model: "CORSA SE ECOFLEX",
    price: "£3,440",
    year: "2015",
    miles: "90,677",
    isMotd: true,
    motExpiryDate: "10 August 2025",
    isTaxed: false,
    taxExpiryDate: "1 April 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 4,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "HIGH SPEC + TOUCH SCREEN. Thank you for viewing. For sale is this metallic black Corsa with good mileage for its age. It has a valid MOT and some great features! Heated seats, Heated steering wheel, auto lights and wipers, and touch screen multimedia. It comes with 2 keys and all usual Vauxhall refinements. Starts and drives well. This vehicle was taken in part exchange by the careful previous owner and has an extensive service history. *Viewing by appointment only. Hadley Automotive is an independent vehicle sourcing service based in Peterborough that you can trust, with many years of experience in the industry. DELIVERY can be arranged nationwide. Any part exchange considered* Vehicle registered: 29/09/2015",
    colour: "Black",
    location:
      "(Hadley Automotive) Peterborough 5 miles away from PE2 8WS. NN6 9QW",
  },
  {
    name: "Vauxhall Corsa",
    make: "VAUXHALL",
    model: "CORSA S ECOFLEX S/S",
    price: "£3,999",
    year: "2015",
    miles: "63,000",
    isMotd: true,
    motExpiryDate: "21 May 2026",
    isTaxed: false,
    taxExpiryDate: "11 July 2024",
    fuelType: "Petrol",
    engineSize: "1.2L",
    noOfOwners: null,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "FULL HISTORY/FULL MOT/G RUNNER. **NATIONWIDE DELIVERY AVAILABLE (ULEZ, COMPLIANT/FREE) **Vauxhall Corsa 1.2 16V SE Euro 5 5dr**Only 2 Former Keeper From New + 63,000 Miles + Full Service History+New Service Done recently + Next Mot Due:21/05/2026+2 keys+Heated Seats+Clean interior/Exterior+Finance Available +Great Spec:Climate Control + Radio Cd Mp3 Player With Aux Input +, Electric Windows + Visit Our Website Over 30. Cars In Stock + ALL DEALER FACILITIES. AVAILABLE.EXTENDED WARRANTIES AVAILABLE. DRIVE AWAY INSURANCE ARRANGED (T&C Apply) VIEWING ADDRESS R&R Motors NEW ROAD BEDFORD MK443LH,, OPEN 7 DAYS A WEEK, 10:00AMto 6:00PM CALL NOW TO ARRANGE A VIEWING 07480 722240, Vehicle registered: 13/01/2015",
    colour: "Silver",
    location: "(R & R Motors Bedford LTD) 55 mins away from PE2 8WS. MK44 3LH",
  },
  {
    name: "Vauxhall Corsa",
    make: "VAUXHALL",
    model: "CORSA SRI ECOFLEX",
    price: "£3,375",
    year: "2015",
    miles: "92,000",
    isMotd: true,
    motExpiryDate: "19 May 2026",
    isTaxed: false,
    taxExpiryDate: "19 May 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 2,
    gearbox: "Manual",
    noOfDoors: 3,
    noOfSeats: 5,
    description:
      "6M WARRANTY! FULL SERV HISTORY. Vauxhall Corsa Excite 2015 - 1.4L, Petrol, Manual - 92,000 Miles - MOT Until 19/05/2026 - FULL SERVICE HISTORY - WATER PUMP DONE - 6 MONTH WARRANTY INCLUDED - HPI CLEAR - ULEZ FREE - Heated Seats and Steering Wheel - Air Conditioning - Touchscreen Infotainment System - Bluetooth, USB & AUX Connectivity - City Steering Mode - Heated Front and Rear Windscreen - Cruise Control - Multi-Functional Leather Steering Wheel - Automatic Headlights - Electric Front Windows and Wing Mirrors - VIDEO AVAILABLE ON REQUEST - FINANCE AVAILABLE - PART EX WELCOME - Car has been incredibly well looked after - Call us on 07729443256 to arrange a viewing. Vehicle registered: 30/03/2015",
    colour: "Black",
    location: "(FHL Autos) 46 mins away from PE2 8WS. MK41 0EP",
  },
  {
    name: "Ford Focus",
    make: "FORD",
    model: "FOCUS TITANIUM X",
    price: "£4,000",
    year: "2015",
    miles: "95,000",
    isMotd: true,
    motExpiryDate: "4 June 2026",
    isTaxed: false,
    taxExpiryDate: "9 June 2025",
    fuelType: "Petrol",
    engineSize: "1.0L",
    noOfOwners: 4,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "**SALE** EVERY CAR REDUCED. Supplied Fully Serviced with 12 Months MOT. Full Service History - 11 Services. New Tyres 01/2025. New Brake Vacum Pump 01/2025. Turbo Valve and Hoses Replaced 01/2025. Heated Front Screen. Bluetooth. 2 Keys At MCS, we prioritize our customers by providing complete peace of mind with our meticulous preparation ensuring that every car meets exacting MCS standards. We're passionate about cars and run our business with honesty, transparency, and respect, as shown by our 5* customer reviews. Every car comes with 12 Months MOT, 6 Months Comprehensive Warranty, 12 Months AA Roadside Assistance, Serviced if required, Fully HPI Clear, Premium Valet and New Number Plates. Full dealer facilities are available at MCS including Test Drives, Competitive Finance Options, Extended Warranty, Part Exchange and Home Delivery. **Please note we do not charge any Admin or Purchase Fees** Extra special cars at regular prices. Vehicle registered: 31/03/2015. Buying with MCS Performance. Performance Specialist in Essex. We are a small friendly team of true car enthusiasts looking to help our valued customers get into their next cars. Whether they're after finance or a quick process, our customers know we are the people to go to when you're buying your next car. With an array of Sporty Performance Hatchbacks and Luxury 4x4s from your favourite manufactures or if you're after the more unique cars, we are here to help! We buy in stock which will suit all customer needs. By investing more into our process we have built a large amount of trust with our customers, with their happiness at the core of all of our decisions.  Our stock is invested in by  us and given our MCS Promise Process to ensure all cars meet the standards of our customers before and after the sale. Our 100+ 5 Star Reviews support this. We have partnered with other enthusiast companies in the area to bring a new level of service  to our customers including remaps, detailing, ceramic coats & more!",
    colour: "Silver",
    location: "(MCS Performance) 66 miles away from PE2 8WS.",
  },
  {
    name: "Vauxhall Corsa",
    make: "VAUXHALL",
    model: "CORSA ENERGY AC ECOFLEX",
    price: "£3,650",
    year: "2015",
    miles: "93,775",
    isMotd: true,
    motExpiryDate: "19 November 2025",
    isTaxed: false,
    taxExpiryDate: "5 June 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 1,
    gearbox: "Manual",
    noOfDoors: 3,
    noOfSeats: 5,
    description:
      "JUST ARRIVED-RESERVE NOW. Secure First Refusal – Reserve Today! Don't miss the opportunity to be first in line for this vehicle. By placing a deposit, you can secure first refusal before it goes live to the public. We're currently preparing the vehicle to an exceptional standard. This includes a fresh service, a minimum of 6 months' MOT with all advisories resolved, and our complimentary 3-month warranty for added peace of mind. Once reserved, we can have the car fully prepared and ready for viewing or collection within 48 hours. If you view and test drive the vehicle and decide it's not right for you, your deposit will be fully refunded—no questions asked. Please note: if you choose not to attend your appointment or fail to view the vehicle, the deposit will be non-refundable. 2015 (65)  VAUXHALL CORSA 1.4i ecoFLEX SRi Hatchback 3dr is offered to you for sale in Pudsey, Leeds, finished in white this  VAUXHALL CORSA 1.4i ecoFLEX SRi Hatchback 3dr is one of many handpicked used cars that used car dealer, Catalina of Stanningley, Pudsey, Leeds have available for sale. Vehicle registered: 29/10/2015. Buying with Catalina Of Stanningley. We are a family owned and run, independent, business. Trading from our sole site since January 1992. We offer a broad range of hand picked, high quality used vehicles. All prepared at our state of the art, preparation facility, meaning that all our vehicles are available to drive away within 30 mins. We have developed great relationships with many of the top new car dealers in the UK to ensure we have the best stock available at all times. As a finance specialist we are full regulated by the FCA and can offer the best finance packages around, both HP and PCP starting at as low as 6.9% APR. If you need any further information don't hesitate to call us on 01132553755 or email us sales@catalinaofstanningley.co.uk.",
    colour: "White",
    location: "(Catalina Of Stanningley) 106 miles away from PE2 8WS.",
  },
  {
    name: "Vauxhall Corsa",
    make: "VAUXHALL",
    model: "CORSA ENERGY AC ECOFLEX",
    price: "£3,995",
    year: "2015",
    miles: "83,856",
    isMotd: true,
    motExpiryDate: "7 December 2025",
    isTaxed: false,
    taxExpiryDate: "26 April 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 2,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "ULEZ✅FSH✅3 MONTHS WARRANTY✅. With only two previous owners, this 2015 Vauxhall Corsa 1.4 i SRi is a great example of a well-cared-for hatchback. Featuring a clear vehicle history check, this Euro 6 petrol Corsa SRi offers a blend of style and practicality. Enjoy modern conveniences such as music streaming via Bluetooth and Bluetooth connectivity for hands-free calls. Air conditioning ensures a comfortable environment, while automatic headlights add to the ease of driving. This Corsa is particularly appealing due to its low insurance group, which means it could be more affordable to insure than similar vehicles. The SRi trim adds a sporty edge to this popular model, making it a practical and stylish choice for everyday driving. Vehicle registered: 08/12/2015",
    colour: "Grey",
    location: "(USK Automotive) 50 mins away from PE2 8WS. SG19 1AW",
  },
  {
    name: "Vauxhall Corsa",
    make: "VAUXHALL",
    model: "CORSA ENERGY AC ECOFLEX",
    price: "£3,450",
    year: "2016",
    miles: "83,765",
    isMotd: true,
    motExpiryDate: "19 March 2026",
    isTaxed: false,
    taxExpiryDate: "8 February 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 2,
    gearbox: "Manual",
    noOfDoors: 3,
    noOfSeats: 5,
    description:
      "mot march 26 +6 month warranty. 2016 vauxhall corsa 1.4 petrol manual 3 doors recent service mot march 2026 83000 miles dab radio with car play black alloys 12 months road tax only 35 pounds  and more hpi clear mileage verified delivery can be arranged 6 months parts and labour warranty included viewing by appointment only. Vehicle registered: 14/03/2016",
    colour: "White",
    location: "(car solutionz) Peterborough 4 miles away from PE2 8WS.",
  },
  {
    name: "Vauxhall Astra",
    make: "VAUXHALL",
    model: "ASTRA SRI",
    price: "£3,890",
    year: "2015",
    miles: "78,977",
    isMotd: true,
    motExpiryDate: "1 September 2025",
    isTaxed: false,
    taxExpiryDate: "28 May 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 3,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "FSH+8+STAMPS+2+KEYS+LOW+TAX. With a full service history and a clear vehicle history check, this 2015 Vauxhall Astra 1.4L petrol i SRi is a dependable choice. The SRi trim adds a sporty edge to this practical hatchback, which meets Euro 6 emission standards. You'll stay cool and comfortable with the included air conditioning. For peace of mind, this Astra comes with a 3-month warranty and a fresh 12 months MOT provided on purchase, so you can drive away with confidence. The last service was completed on 20th June 2025, ensuring it's ready for the road. This Vauxhall Astra stands out with its low insurance group, potentially saving you money on your premiums compared to similar vehicles. Plus, the large boot space offers ample room for luggage, shopping, or anything else you need to carry. This makes it a practical option for families or anyone who needs extra storage. Vehicle registered: 31/12/2015. Buying with HOLBEACH CARS. Holbeach Cars LTD - Your Trusted Local Dealership! Looking for a reliable used car? Look no further! At Holbeach Cars, we offer a wide selection of high-quality, pre-owned vehicles to suit every budget and lifestyle. Why Choose Us? - Extensive Inventory: From compact cars to family SUVs, we have it all! - Affordable Prices: Competitive pricing to ensure you get the best deal. - Quality Assurance: All our vehicles undergo a thorough inspection and come with a warranty. - Financing Options: Flexible financing solutions to fit your budget. - Customer Satisfaction: Our friendly staff is here to help you every step of the way. Visit Us Today! 📍 Location: Fen Road, Holbeach, PE12 8QD. 📞 Call Us: 01406841307. 🌐 Website: https://holbeachcars.co.uk/",
    colour: "White",
    location: "(HOLBEACH CARS) 45-47 mins away from PE2 8WS. PE12 8QD",
  },
  {
    name: "Vauxhall Mokka",
    make: "VAUXHALL",
    model: "MOKKA EXCLUSIV S/S",
    price: "£3,499",
    year: "2015",
    miles: "100,000",
    isMotd: true,
    motExpiryDate: "25 August 2025",
    isTaxed: false,
    taxExpiryDate: "11 April 2025",
    fuelType: "Petrol",
    engineSize: "1.6L",
    noOfOwners: 1,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "Just Serviced/2Key/LongMot/Vgc. Recently serviced in April 2025, this 2015 Vauxhall Mokka i Exclusiv is a great example of a reliable and well-maintained vehicle. Featuring a 1.6L petrol engine and a Euro 6 emission class, this Mokka Exclusiv offers a blend of performance and efficiency. You'll also benefit from Bluetooth connectivity, making hands-free calls and music streaming simple and safe. The electronic dual-zone climate control ensures both the driver and passengers can set their ideal temperature. Parking is made easier with front and rear parking distance sensors, while automatic lighting control takes the stress out of driving in changing light conditions. For peace of mind, this Mokka comes with a 3-month warranty and will have a 12-month MOT provided on purchase. One of the great things about this vehicle is that it falls into a low insurance group, which means it could be more affordable to insure than other similar vehicles. OPEN 7 DAYS A WEEK 9:30AM to 6:30PM|CALL NOW TO ARRANGE A VIEWING 01234677432 & RESERVE THIS VEHICLE. Vehicle registered: 18/03/2015. Buying with Affordable Car Centre Ltd. If you are looking for a quality used car in Bedford area then you have reached the right place. AFFORDABLE CAR CENTRE is a specialist used car dealer based in Bedford, Bedfordshire. We are proud to offer you a first class customer service and a very competitive pricing, so please browse our stock list At www.Affordablecarcentre.co.uk we stock a range of quality used cars to suit all budgets so we are sure to have the right car for you. If you are looking for a quality second hand car then DO NOT DELAY CALL US TODAY to book a test drive. In order to offer cars to suit everyone we make sure that we update our stock list regularly. It is therefore always worth giving us a call even if you don’t see what you are looking for on our website. We realize that buying car can be a daunting experience, but do not worry! we are well established within the bedfordshire area and come with a great reputation this is the reason why many of our customers keep coming back to us.",
    colour: "Grey",
    location: "(Affordable Car Centre Ltd) 39 mins away from PE2 8WS. MK44 3LH",
  },
  {
    name: "Vauxhall Astra",
    make: "VAUXHALL",
    model: "ASTRA EXCITE",
    price: "£3,995",
    year: "2015",
    miles: "78,149",
    isMotd: true,
    motExpiryDate: "22 March 2026",
    isTaxed: false,
    taxExpiryDate: "10 June 2025",
    fuelType: "Petrol",
    engineSize: "1.6L",
    noOfOwners: 1,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "Vehicle registered: 22/09/2015. Buying with Indus Car Sales Ltd. Tired of your old car? 👉 Looking for the perfect car for your son or daughter? 👉 Want to surprise your partner with a car for a special occasion? At Indus Car Sales Ltd, we’ve got you covered! We’ll not only deliver your new car straight to your doorstep, but we’ll also buy your old one. We call our customers THE BOSS – because YOU are our top priority! That’s why we offer a carefully selected range of high-quality cars at incredibly affordable prices. We’re BIG on quality, and we know how important it is to find the right car. Every vehicle we sell is thoroughly quality-checked before it ever hits the forecourt, ensuring peace of mind for our valued customers. As an AA-approved dealer, we provide: 12-month MOT (if the MOT is due in less than 6 months). 3-month extendable warranty by AA. Nationwide delivery, no matter where you are in the UK. Based in Stoke-on-Trent (ST3 1PF), we’re a family-owned business that prioritises building strong, lasting relationships with our customer",
    colour: "Silver",
    location: "(Indus Car Sales Ltd) 53 mins away from PE2 8WS.",
  },
  {
    name: "Vauxhall Mokka",
    make: "VAUXHALL",
    model: "MOKKA EXCLUSIV S/S",
    price: "£3,995",
    year: "2016",
    miles: "92,300",
    isMotd: true,
    motExpiryDate: "8 April 2026",
    isTaxed: false,
    taxExpiryDate: "7 March 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 4,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "New mot +delivery + 2 keys. This is a 2016 Vauxhall Mokka 1.4L Petrol SE i Turbo SE car, which meets Euro 6 emission standards and has a clear vehicle history check. The car is equipped with heated front seats and a heated steering wheel, perfect for those cold mornings. The dual-zone electronic climate control ensures a comfortable environment for both the driver and passenger. Front parking distance sensors make parking easier, and Bluetooth connectivity allows for hands-free calls and audio streaming. With an acceleration of 0-60mph in 9.3 seconds, this car is quicker off the mark than other similar vehicles, making it ideal for both city driving and longer journeys. T B MOTORS IS A FAMILY RUN BUSINESS, ESTABLISHED OVER 3  YEARS AGO , OFFERING QUALITY USED VEHICLES WITH PROFESSIONAL SERVICE. EACH OF OUR VEHICLES COMES WITH A MINIMUM OF 6 MONTHS MOT AND 3 MONTHS WARRANTY. IF YOU HAVE ANY QUARRIES, PLEASE RING ON 07858659147, ONE OF OUR TEAM MEMBERS WOULD LOVE TO HELP. WE OFFER PART EXCHANGE ON YOUR EXISTING VEHICLE AND COMPETITIVE FINANCE PACKAGES (SUBJECT TO STATUS) - - NATIONWIDE DELIVERY AVAILABLE PLEASE RING FOR A QUOTE. BOOK A TEST DRIVE NOW ON 07858659147. STANDARD BUSINESS HOURS ARE 10:00 AM 17:00 PM MONDAY TO FRIDAY, SATURDAY AND SUNDAY 10 AM Till 4:30 PM , APPOINTMENTS ARE AVAILABLE OUTSIDE HOURS ON REQUEST. Vehicle registered: 17/05/2016. Buying with T B MOTORS BEDFORD LTD. we are a family run business , we prioritize every single car and customer with care ,we are happy to assist you with any enquiry with smile ,every single car is inspect  by our mechanic before its goes in to sales , we do delivery services for nationwide with competitive rates , and click and collect service, ",
    colour: "White",
    location: "(T B MOTORS BEDFORD LTD) 52 mins away from PE2 8WS. MK44 3LH",
  },
  {
    name: "Vauxhall Corsa",
    make: "VAUXHALL",
    model: "CORSA DESIGN",
    price: "£3,599",
    year: "2016",
    miles: "97,881",
    isMotd: true,
    motExpiryDate: "27 January 2026",
    isTaxed: false,
    taxExpiryDate: "26 February 2025",
    fuelType: "Petrol",
    engineSize: "1.2L",
    noOfOwners: 1,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "Ideal 1st car+1 yr mot+media. Ideal 1st car. Comes with AA warranty. 2 previous owners only. Comes with 12 months mot. Comes with new service. Media connectivity. Usb. Air con. Finance available. Delivery available. Vehicle registered: 27/01/2016. Buying with Big Bob Car Sales. Welcome to Big Bob Cars Sales Ltd in Hull, Yorkshire. We have a wide range of used car for sale.. As an independent garage we pride ourselves on friendly customer service with a great choice of affordable vehicles to suit your motoring needs and your budget. Our sales team will work with you to find the vehicle of your choice and help with each step of the buying process. If you can't find the car you're looking for why not get in contact with our friendly sales team today.",
    colour: "Grey",
    location: "(Big Bob Car Sales) 84 miles away from PE2 8WS.",
  },
  {
    name: "Vauxhall Corsa",
    make: "VAUXHALL",
    model: "CORSA SE ECOFLEX",
    price: "£3,990",
    year: "2015",
    miles: "72,000",
    isMotd: true,
    motExpiryDate: "14 June 2026",
    isTaxed: false,
    taxExpiryDate: "1 June 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 3,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "FSH + MOT + WATERPUMP @ 72k. Here is my 2015 Vauxhall Corsa Sri. Runs and drives great with no unwanted noises. Full service history. Great condition. Water pump changed at 72k. Cruise control and much more. For any further questions please contact. Vehicle registered: 04/09/2015",
    colour: "Silver",
    location: "(A.H cars) Peterborough 4 miles away from PE2 8WS.",
  },
  {
    name: "Vauxhall Mokka",
    make: "VAUXHALL",
    model: "MOKKA EXCLUSIV S/S",
    price: "£3,680",
    year: "2017",
    miles: "92,000",
    isMotd: true,
    motExpiryDate: "20 March 2026",
    isTaxed: false,
    taxExpiryDate: "15 April 2025",
    fuelType: "Petrol",
    engineSize: "1.4L",
    noOfOwners: 2,
    gearbox: "Manual",
    noOfDoors: 5,
    noOfSeats: 5,
    description:
      "This 2017 Vauxhall Mokka 1.4i Turbo Exclusiv SUV with 92,000 miles on the clock and has full service history is a reliable, spacious SUV perfect for long distance journeys. Powered by a petrol engine and equipped with a manual transmission, it is ULEZ compliant and MOT expires on 20/03/2026. With 5 seats, 5 doors, and 18in Alloy Wheels, this Euro 6 (s/s) vehicle offers a comfortable and stylish driving experience. Additional features include 12V Power Socket, 20 Watts Per Channel Output, and 60-40 Split-Folding Rear Seat Back, making it a practical choice for families or individuals who value both comfort and versatility. Vehicle registered: 21/03/2017",
    colour: "Black",
    location:
      "(RAVA BEST CAR DEALS LIMITED) 10 mins away from PE2 8WS. PE1 5YB",
  },
]
