name: CI on Testing

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Format code (Prettier)
        run: npm run format

      - name: Lint code (ESLint)
        run: npm run lint

      - name: Build site (static)
        run: npm run generate
        env:
          NODE_ENV: production
          NUXT_APP_BASE_URL: /
